name: CI

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the sources"
        uses: actions/checkout@v2.3.1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          distribution: "adopt"
          java-version: 11
      - name: Setup Bazelisk
        uses: holvonix-open/setup-bazelisk@v0.6.1
      - name: "Building"
        run: bazel build //...
